apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBqI6rLzv1XbNJ/I2x1R5QIGVifffSmRvBJSbClkfIksKfxQSpHxBQT18/9V8uUEBJL9166yf2gHbriozh+kBJBtnP6DpG1zSSvRMpiqvImcCWskopE5kRUg7p8TD45Rc3DtvceT3NHpl9ypcXeipfkSX1LDMV4+uQPkDGvN/exWvskLA2A0MgG6j2E4sH7aVGqfPDbt1+aOZ+x8K9v7/tR06unXoyfevnHrjoIu2tX7JQqFmtbC53LMUkffPmLJUisVqRzwPyHYIULQlIl5eLByKXuHYN+JFMGvAy57LHyGfj2cuASIwkCwMLrl8qCepQ1kYrJ7/5wxockAB2b7Gl+EXbjU5xzb65L7G7gPszL3Vh3uIXz3AprMfRgSDrZpLsPHSedXEj/To3Jlma2Lj/M7bvrogHu7cRR9fXaesEmVaDtGPtMYyq7wB1lDW4tyKM4C44jnAsZcN2ElLbJNZC+6ZURPKBJUSJBu/XKsh4bxzCmrcGWWzdu/e7GMHoYCe5GZB/zxZDuIzHkjoJWjaUcsEM4fLbuTK65GR07EHuyNzFeg6vaRym/Hhi+jFHA2yltK0gncchUprHKSe2Yzu5GdIVbdaZdYKDwWiaJExKe/V2sCuYe+1SCNtpBQgPbmeBwKfDRiOmkp23rt9jwdWzxErtg/kw1yEVFMM7XzID+oUUdh8fEvikOtRInGP1zYvjmiBl3DnkoyP3BGgOVN04/OgmmKKNPk+SpkhTGpvAms3sYeLx4A5J8kjHY4jptbLyKQ47pAqoNI4fQD62H67rFTLEWyAvqjVZDBYdG6VnTnzsPWTh9fEgva9NV99ksTML/YDBSJAyumyasRKkc2nkhnvDze4ft5nAwZSbXVnfeV8W22RaGT63wqV1Ql/g=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

