apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDvPP//h0+j9U46ZFBEzlIRZhgnaVfTL15Sushqhk6HnfJEQG8ypQ7OSfId53s6tvy8I3cyui6ceYOdR/ST+KaiOp2yezfqkESimoYBFawOKJZ4iFp8NkIWQtO0tDJtAbqKy29iHrV+OaDjGt2Gi0hjBFew89F6+/1LI7yB3kozEGm966pS73p05dN4CIaAWqM4XX9tgjLK8G5yPkMg+ml/8M3m6Bh/Sgg+WeVHUbLTAaU76UXxNIb3Ql1P4qPaZixQ9SQ5lnC8EbnGosrPc0DW0H4Tg75/qGVTIeCqeqJRe/9bhLGYeZdHA834RUhgxTVOfJjgc+0OsFGrsSBinnbXT97+lTXA9AS5WG1o/pTFpm/7vFMonE/UOCLMS7p5q1a71F8qaAPGRAhwcmKuqKDagFYMZfNpF5cnoXej2+Cq+pNGL813pjCEWIyGycz5uzn4PnurV/wSANzPyhEQ6FHMPqhj8NHgw6IlSMCHhlyxlRQ50JAR+CaNXo5VMhVJnn5bA/sR1Kw6ghSl4AnjxEYXbyLOTffuczzKH2u7QUqiRg4P+gA8zWIJjT/tYp5fUKGSDzdw6Xc7Va/d3fhnpIdo3qmhLve+Wvg6+FxgDzdxP39hW8kKL6XhJWv563fxdc2usXxD+SVpDEMHWcvd1BUpPFa99tbaF8S1jwv950e926XIdfTB4i06VfCVdO4580YSa/l7NZVfbOlE2WY4NI0cflG8Tzan/2sKlquPK5kuUpUHz9YwlGhE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

